dist: trusty
sudo: required

language: scala

scala:
   - 2.11.11
jdk:
  - openjdk8
  - jdk8

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

services:
  - docker

before_script:
  - ./local-install-enry-java.sh
  - docker run --privileged -d -p 9432:9432 --name bblfsh bblfsh/server

script:
  - ./sbt ++$TRAVIS_SCALA_VERSION jacoco:cover
  - ./sbt assembly

after_success:
  - bash <(curl -s https://codecov.io/bash)
